name: PyPI deployer
on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_dispatch:

jobs:
  # Build and deploy manylinux wheel
  Linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [x86_64, aarch64]
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        if: ${{ matrix.platform == 'aarch64' }}
        uses: docker/setup-qemu-action@v1
      - name: Build and upload manylinux wheels
        if: ${{ matrix.platform == 'x86_64' }}
        uses:  mozman/manylinux-wheel-builder@master
        with:
          python-versions: "3.7, 3.8, 3.9, 3.10"
        # if true then github actions won't stop even if build for this job fails
        continue-on-error: true
      - name: Build manylinux aarch64 wheels
        if: ${{ matrix.platform == 'aarch64' }}
        uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2014_aarch64
        with:
          python-versions: 'cp37-cp37m cp38-cp38 cp39-cp39 cp310-cp310'
          build-requirements: 'cython'
        # if true then github actions won't stop even if build for this job fails
        continue-on-error: true
      - name: Publish manylinux aarch64 wheels to PyPI
        run: |
          twine upload dist/*_aarch64.whl

  # Deploy source distribution
  Source-dist:
    runs-on: windows-latest
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Create source distribution
        run: python setup.py sdist --formats=zip
      - name: Upload source distribution
        run: |
          pip install twine
          twine upload dist/*
        continue-on-error: true

  # Build and deploy wheels for macOS and Windows
  Matrix-build:
    runs-on: ${{ matrix.os }}
    env:
      TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
      TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build binary wheels
        run: |
          pip install wheel cython
          python setup.py bdist_wheel
      - name: Upload binary wheels
        run: |
          pip install twine
          twine upload dist/*
        continue-on-error: true
